#!/bin/sh /etc/rc.common
# Copyright (C) 2025  Fish <ss@ss8.io>

START=99
USE_PROCD=10

LOGFILE="/tmp/h29k_sysinfo.log"N

start_service() {
    logger -t H29K "Starting H29K Sysinfo Service"
    procd_open_instance
    procd_set_param command /usr/bin/h29k_sysinfo
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    logger -t H29K "Stopping H29K Sysinfo Service"
    killall h29k_sysinfo 2>/dev/null
}

restart_service() {
    stop_service
    start_service
}